In [1]:
import numpy as np
import csv
import time
import sys
from numpy import genfromtxt

In [5]:
b=range(1000)#size of the array
print(sys.getsizeof(5)*len(b))

c=np.arange(1000)
print(c.size*c.itemsize)



28000
8000


In [20]:
#1D array
#Dimension,Shape,Size,Length & Type of array

import numpy as np

a = np.array([2,3,4,5,1,9])
print(a)
print("Dimensions:",a.ndim)
print("Shape:",a.shape)
print("size:",a.size)
print("Length:",len(a))
print(type(a))

#2D array

b = np.array([[2,3,4,5],[4,6,8,9]])
print(b)
print("Dimensions:",b.ndim)
print("Shape:",b.shape)
print("size:",b.size)
print("Length:",len(b))
print(type(b))

#3D array

c = np.array([[2,3,4,5],[4,6,8,9]],
             [[2,6,7,5],[8,9,6,2]])
print(c)
print("Dimensions:",c.ndim)
print("Shape:",c.shape)
print("size:",c.size)
print("Length:",len(c))
print(type(c))






[2 3 4 5 1 9]
Dimensions: 1
Shape: (6,)
size: 6
Length: 6
<class 'numpy.ndarray'>
[[2 3 4 5]
 [4 6 8 9]]
Dimensions: 2
Shape: (2, 4)
size: 8
Length: 2
<class 'numpy.ndarray'>


TypeError: ignored

In [ ]:
empid =np.arange(101,111)
sal = np.random.randint(10000,20000,10)
empid
sal

np.mean(sal)
np.sum(sal)

empid + sal #add empid[0] with sal[0]
np.add(empid,111) #adds 111 to every item in an array
empid[0:6:2]#slicing can be used in np

empid.size #counts the no of items in the array

idx = np.where(empid > 105)#it returns the index positions of the value that matches the conditions
empid[idx]#pass index to get the values

newempid = np.arange(111,116)
newempid

empid = np.append(empid , newempid)
empid

print(np.sort(sal))#asc
print(np.sort(sal)[::-1])#desc








[10173 11774 13101 13790 16238 16548 16681 16848 18050 19310]
[19310 18050 16848 16681 16548 16238 13790 13101 11774 10173]
